- hosts: all

  tasks:
    - name: 'Instalar net-tools'
      apt:
        update_cache: yes
        cache_valid_time: 3600 #1 hora
        name: net-tools
        state: latest
      become: yes

    - name: 'Instalar dependencias'
      apt:
        update_cache: yes
        cache_valid_time: 3600 #1 hora
        name:  ['apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']
        state: latest
      become: yes

    - name: 'Instalar Docker'
      apt:
        update_cache: yes
        cache_valid_time: 3600 #1 hora
        name:  ['docker', 'docker.io', 'docker-compose']
        state: latest
      become: yes

    - name: Verifica se o Docker Swarm está habilitado
      shell: docker info
      changed_when: False
      register: docker_info
      become: true

    - name: Listar nodes
      command: docker node ls
      become: true
      when: "'manager' in group_names"

    - name: Atualizar serviço banco de dados
      command: docker service update encaminhador_db --force
      become: true
      when: "'manager' in group_names"

    - name: Atualizar serviço web
      command: docker service update encaminhador_web --force
      become: true
      when: "'manager' in group_names"

#    - name: Dar permissão
#      command: chown -R $USER:$USER .
#      become: true
#      args:
#        chdir: /vagrant/docker/

#    - name: Subir compose
#      command: docker-compose up -d
#      become: true
#      args:
#        chdir: /vagrant/docker/

#    - name: makemigrations
#      command: docker-compose exec node python manage.py makemigrations
#      become: true
#      args:
#        chdir: /vagrant/docker/
#    - name: migrate
#      command: docker-compose exec node python manage.py migrate
#      become: true
#      args:
#        chdir: /vagrant/docker/
