image: docker:stable

stages:
- pre-build
- build
- test
- deploy


#build-docker:
#  services:
#  - docker:dind
#  before_script:
#  - docker info
#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
#  stage: pre-build
#  - docker build -t django docker/.
#  - docker tag django schulzdaniel/django:1.1
#  - docker push schulzdaniel/django:1.1
#  tags:
#  - executor-tarefas


build-project:
  image: schulzdaniel/django:1.1
  services:
  - docker:dind
  - name: postgres
    alias: db
  variables:
    POSTGRES_DB: 'postgres'
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'postgres'
  stage: build
  tags:
  - executor-tarefas
#  dependencies:
#  - build-docker
  script:
  - python docker/manage.py makemigrations
  - python docker/manage.py migrate


test-project:
  image: schulzdaniel/django:1.1
  stage: test
  services:
  - docker:dind
  - name: postgres
    alias: db
  variables:
    POSTGRES_DB: 'postgres'
    POSTGRES_USER: 'postgres'
    POSTGRES_PASSWORD: 'postgres'
  dependencies:
  - build-project
  tags:
  - executor-tarefas
  script:
  - python docker/manage.py test
