image: docker:stable

stages:
- pre-build
- build
- test
- deploy

services:
- docker:dind

before_script:
- docker info
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD


build-docker:
  stage: build
  script:
  - docker build -t django docker/.
  - docker tag django schulzdaniel/django:1.1
  - docker push schulzdaniel/django:1.1

build-project:
  stage: build
  tags:
  - executor-tarefas
  dependencies:
  - build-docker
  script:
  - echo "runner"
