image: docker:stable

services:
- docker:dind

before_script:
- docker info
- docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD


build-docker:
  stage: build
  script:
  - docker build -t schulzdaniel/django:1.1 docker/.
  - docker tag django:1.1  schulzdaniel/django:1.1
  - docker push schulzdaniel/django:1.1
