version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - docker-network
    volumes:
      - pgdata:/var/lib/postgresql/data
#      - pgconf:/etc/postgresql
#      - pglog:/var/log/postgresql

#    command: chown postgres /var/lib/postgresql/data/
  node:
    build: .
    command: python manage.py runserver 0.0.0.0:8889
    volumes:
      - .:/code
    ports:
      - "8889:8889"
    depends_on:
      - db
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  pgdata:
#  pgconf:
#  pglog:
