# Generated by Django 3.1.4 on 2020-12-27 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='outro_campo',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='outro_campo',
        ),
        migrations.AddField(
            model_name='evento',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidente',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidente',
            name='hostname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
