# Generated by Django 3.1.4 on 2020-12-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0002_auto_20201227_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='equipe',
            field=models.CharField(choices=[('1', 'GPROM-31'), ('2', 'GPROM-32'), ('3', 'GPROM-33'), ('4', 'GPROM-35'), ('5', 'GPROM-73'), ('6', 'GSERV-AU'), ('7', 'DAT-SP')], default='1', max_length=1),
        ),
    ]
