# Generated by Django 3.1.4 on 2020-12-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0003_incidente_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidente',
            name='equipe',
            field=models.CharField(choices=[('0', 'GSERV-AU'), ('1', 'DAT-SP'), ('2', 'GPROM-31'), ('3', 'GPROM-32'), ('4', 'GPROM-33'), ('5', 'GPROM-35'), ('6', 'GPROM-72')], default='1', max_length=1),
        ),
    ]
