# Generated by Django 3.1.4 on 2021-01-28 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0006_auto_20210128_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='OpenTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 15, 22, 44, 645843), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='UpdateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 15, 22, 44, 645934), editable=False),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Area',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Assignee',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='AssignmentGroup',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Category',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Contact',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='EquipeCriador',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Impact',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='IncidentID',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='OpenTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 15, 22, 44, 647150)),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='OpenedBy',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Service',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Status',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Subarea',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='TelefoneSolicitante',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='UpdateBy',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='UpdateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 15, 22, 44, 647227)),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='Urgency',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='data_evento',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 15, 22, 44, 647248)),
        ),
    ]
