# Generated by Django 3.1.4 on 2021-01-28 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarmes', '0013_auto_20210128_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidente',
            old_name='hostname',
            new_name='Hostname',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_evento',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='data_evento',
        ),
        migrations.RemoveField(
            model_name='incidente',
            name='equipe',
        ),
        migrations.AlterField(
            model_name='evento',
            name='OpenTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 17, 6, 36, 68976), editable=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='UpdateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 17, 6, 36, 69074), editable=False),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='OpenTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 17, 6, 36, 69612)),
        ),
        migrations.AlterField(
            model_name='incidente',
            name='UpdateTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 28, 17, 6, 36, 70346)),
        ),
    ]
